FROM chenjr0719/afs-docker-images:openpai-deepo

# Install Jupyter
RUN pip install https://github.com/owen198/notebook/raw/master/dist/notebook-5.6.0.dev0-py2.py3-none-any.whl \
    ipykernel==4.9.0 \
    ipython==6.5.0 \
    ipython_genutils==0.2.0 \
    ipywidgets==7.4.0 \
    jupyter==1.0.0 \
    jupyter_client==5.2.3 \
    jupyter_console==5.2.0 \
    jupyter_core==4.4.0 \
    nbconvert==5.3.1 \
    nbformat==4.4.0 \
    https://github.com/benchuang11046/afs/releases/download/1.3.0/afs-1.3.0-py3-none-any.whl